# tomcat configuration
server:
    port: 8081
    servlet :
      context-path: /api



# mybatis configuration
mybatis: 
  configuration:
    map-underscore-to-camel-case: true

# database configuration
spring.datasource: 
  url: jdbc:mysql://localhost:3306/myappdb?serverTimezone=GMT%2B8
  username: root
  password: root
  driverClassName: com.mysql.jdbc.Driver

# dev/release
spring.profiles.active: dev
#spring.profiles.active: prd

# project
jp.co.nttdata.myapp:
  refreshToken.expirationInterval: 5400000
  accessToken.expirationInterval: 86400000

spring:
  mail:
    host: smtp.163.com
    port:
    username: medicialbbs@163.com
    password: root12345